# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
version: 2

before:
  hooks:
    # You may need to run go mod tidy before build
    - go mod tidy

builds:
  - id: concat
    main: ./cmd/concat
    binary: concat
    goos:
      - linux
      - windows
      - darwin
  - id: opt
    main: ./cmd/opt
    binary: opt
    goos:
      - linux
      - windows
      - darwin

archives:
  - format: tar.gz
    files:
      - README.md
      - LICENSE
checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
